

















  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'
  github: '//github.com/kaeyleo'
  home: '/'
  input: GFM
  instagram: '//www.instagram.com/steveliaocn'
  juejin: '//juejin.im/user/57a6f434165abd006159b4cc'
  since: 2017
  tags: '/tags.html'
  weibo: '//weibo.com/lovecolcol'
# Author 配置博主信息
# Build settings
# Comments 评论功能
# Footer
# if you don't need baseurl, you should leave this value blank.
# Markdown
# MathJax 公式支持 by Ray-Eldath
# Navigation links
# Night mode
# Permalink
# Plugins
# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
# RSS
# Search
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
# Share
# Site settings 配置站点
# SNS settings 配置社交网站
# Tags 设置标签
# theme color 主题皮肤
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
author: 'HackZ'
avatar: '/assets/img/profile.png'
baseurl: 'https://dyzsoft.github.io/jekyll-theme-H2O/'
bio: '前端开发者，热爱技术&设计，简单乐观爱创造'
comments:
description: 'WebSecurity is truly 黑不得了'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']
footer:
highlighter: rouge
keyword: '张宇明,Web Security'
kramdown:
markdown: kramdown
mathjax: true
nav:
nickname: '悟空'
nightMode: true
paginate: 6
paginate_path: 'page:num'
permalink: /:year/:month/:day/:title.html
plugins: [jekyll-paginate]
postPatterns: 'circuitBoard'
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value
recommend-tags: true # whether or not display recommend-tags on the sidebar
RSS: false
search: true
sns:
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']
social-share: true
theme-color: 'default'  # pink or default
title: 'HackZ'
url: 'https://github.com/zyzgc1997/zyzgc1997.github.io/' # your host